backend:
  name: github
  repo: APNA_GITHUB_USERNAME/APNA_REPO_NAME # Yahan actual GitHub Username/Repo dalein (e.g., user/historias)
  branch: main
  base_url: "https://decap-cms-oauth-provider.vercel.app" # Free Auth Proxy
  auth_endpoint: "/auth"

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Historias"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
